name: GreenRiverOrdinance
favicon: null
layout_spectrum: 0.6218518984969705
typography_spectrum: 0.80213802610524
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.4672097130678594
  lightness: 0.9964713593944907
  saturation: 0.3016238010022789
  rhythmicContrast: 0.49145985790528357
purpose: []
